import { ZoneProps } from "@/types/Types";

export const ZoneData:ZoneProps[] = [
    {
        id: "1",
        name: "Zone A",
        country: "USA",
        state: "California",
        registrants: 150,
        groups: 10,
        churches: 5,
        coordinators: 3,
        volunteers: 20,
    },
    {
        id: "2",
        name: "Zone B",
        country: "USA",
        state: "Texas",
        registrants: 200,
        groups: 15,
        churches: 8,
        coordinators: 4,
        volunteers: 30,
    },
    {
        id: "3",
        name: "Zone C",
        country: "Canada",
        state: "Ontario",
        registrants: 120,
        groups: 8,
        churches: 4,
        coordinators: 2,
        volunteers: 15,
    },
    {
        id: "4",
        name: "Zone D",
        country: "UK",
        state: "England",
        registrants: 180,
        groups: 12,
        churches: 7,
        coordinators: 5,
        volunteers: 25,
    },
    {
        id: "5",
        name: "Zone E",
        country: "Australia",
        state: "New South Wales",
        registrants: 90,
        groups: 6,
        churches: 3,
        coordinators: 2,
        volunteers: 10,
    },
    {
        id: "6",
        name: "Zone F",
        country: "USA",
        state: "Florida",
        registrants: 160,
        groups: 11,
        churches: 6,
        coordinators: 4,
        volunteers: 22,
    },
    {
        id: "7",
        name: "Zone G",
        country: "Germany",
        state: "Bavaria",
        registrants: 130,
        groups: 9,
        churches: 5,
        coordinators: 3,
        volunteers: 18,
    },
    {
        id: "8",
        name: "Zone H",
        country: "Brazil",
        state: "Sao Paulo",
        registrants: 220,
        groups: 14,
        churches: 9,
        coordinators: 6,
        volunteers: 35,
    },
    {
        id: "9",
        name: "Zone I",
        country: "South Africa",
        state: "Gauteng",
        registrants: 110,
        groups: 7,
        churches: 4,
        coordinators: 2,
        volunteers: 12,
    },
    {
        id: "10",
        name: "Zone J",
        country: "India",
        state: "Maharashtra",
        registrants: 300,
        groups: 20,
        churches: 12,
        coordinators: 8,
        volunteers: 50,
    },
    {
        id: "11",
        name: "Zone K",
        country: "Japan",
        state: "Tokyo",
        registrants: 140,
        groups: 10,
        churches: 5,
        coordinators: 3,
        volunteers: 15,
    },
    {
        id: "12",
        name: "Zone L",
        country: "Mexico",
        state: "Jalisco",
        registrants: 190,
        groups: 13,
        churches: 6,
        coordinators: 5,
        volunteers: 28,
    },
    {
        id: "13",
        name: "Zone M",
        country: "France",
        state: "Île-de-France",
        registrants: 250,
        groups: 18,
        churches: 10,
        coordinators: 7,
        volunteers: 40,
    },
    {
        id: "14",
        name: "Zone N",
        country: "Italy",
        state: "Lazio",
        registrants: 170,
        groups: 12,
        churches: 7,
        coordinators: 4,
        volunteers: 20,
    },
    {
        id: "15",
        name: "Zone O",
        country: "Russia",
        state: "Moscow",
        registrants: 80,
        groups: 5,
        churches: 3,
        coordinators: 2,
        volunteers: 8,
    },
];