export const ChurchData = [
    {
        id: "1",
        name: "Grace Community Church",
        country: "USA",
        state: "California",
        pastor: "John Doe",
        registrants: 200,
        youth: 50,
        groups: 10,
        zone: "West",
        coordinators: 5,
        volunteers: 30,
    },
    {
        id: "2",
        name: "Faith Baptist Church",
        country: "USA",
        state: "Texas",
        pastor: "Jane Smith",
        registrants: 150,
        youth: 30,
        groups: 8,
        zone: "South",
        coordinators: 4,
        volunteers: 25,
    },
    {
        id: "3",
        name: "Hope Church",
        country: "Canada",
        state: "Ontario",
        pastor: "Michael Johnson",
        registrants: 300,
        youth: 70,
        groups: 12,
        zone: "Central",
        coordinators: 6,
        volunteers: 40,
    },
    {
        id: "4",
        name: "Unity Church",
        country: "UK",
        state: "London",
        pastor: "Sarah Williams",
        registrants: 180,
        youth: 40,
        groups: 9,
        zone: "Europe",
        coordinators: 5,
        volunteers: 20,
    },
    {
        id: "5",
        name: "Redeemed Church",
        country: "Australia",
        state: "New South Wales",
        pastor: "David Brown",
        registrants: 220,
        youth: 60,
        groups: 11,
        zone: "Oceania",
        coordinators: 5,
        volunteers: 35,
    },
    {
        id: "6",
        name: "New Life Church",
        country: "USA",
        state: "Florida",
        pastor: "Emily Davis",
        registrants: 250,
        youth: 55,
        groups: 15,
        zone: "East",
        coordinators: 7,
        volunteers: 45,
    },
    {
        id: "7",
        name: "Cornerstone Church",
        country: "USA",
        state: "New York",
        pastor: "Christopher Wilson",
        registrants: 175,
        youth: 35,
        groups: 7,
        zone: "Northeast",
        coordinators: 4,
        volunteers: 22,
    },
    {
        id: "8",
        name: "Living Waters Church",
        country: "USA",
        state: "Illinois",
        pastor: "Jessica Taylor",
        registrants: 130,
        youth: 25,
        groups: 6,
        zone: "Midwest",
        coordinators: 3,
        volunteers: 15,
    },
    {
        id: "9",
        name: "Shepherd's Flock",
        country: "USA",
        state: "Washington",
        pastor: "Brian Martinez",
        registrants: 160,
        youth: 45,
        groups: 10,
        zone: "Pacific",
        coordinators: 6,
        volunteers: 28,
    },
    {
        id: "10",
        name: "Covenant Church",
        country: "Canada",
        state: "British Columbia",
        pastor: "Laura Anderson",
        registrants: 140,
        youth: 20,
        groups: 5,
        zone: "West",
        coordinators: 3,
        volunteers: 18,
    },
    {
        id: "11",
        name: "Faith Fellowship",
        country: "USA",
        state: "Ohio",
        pastor: "Kevin Harris",
        registrants: 190,
        youth: 50,
        groups: 9,
        zone: "Midwest",
        coordinators: 5,
        volunteers: 24,
    },
    {
        id: "12",
        name: "Promise Church",
        country: "Australia",
        state: "Victoria",
        pastor: "Natalie Lewis",
        registrants: 170,
        youth: 30,
        groups: 8,
        zone: "Oceania",
        coordinators: 4,
        volunteers: 20,
    },
    {
        id: "13",
        name: "Victory Church",
        country: "New Zealand",
        state: "Auckland",
        pastor: "Daniel Hall",
        registrants: 210,
        youth: 65,
        groups: 12,
        zone: "Oceania",
        coordinators: 6,
        volunteers: 38,
    },
    {
        id: "14",
        name: "Joyful Hearts Church",
        country: "USA",
        state: "Georgia",
        pastor: "Samantha Young",
        registrants: 230,
        youth: 55,
        groups: 11,
        zone: "South",
        coordinators: 5,
        volunteers: 32,
    },
    {
        id: "15",
        name: "Eagle's Nest Church",
        country: "USA",
        state: "Colorado",
        pastor: "Matthew King",
        registrants: 140,
        youth: 25,
        groups: 7,
        zone: "West",
        coordinators: 4,
        volunteers: 19,
    },
];